version: '3.8'

services:
  web:
    build: ./php
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - myapp-network
    volumes:
      - ./php:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: TurnosDB  # Nombre de la base de datos
      MYSQL_USER: user          # Nombre de usuario
      MYSQL_PASSWORD: user_password  # Contraseña del usuario
    networks:
      - myapp-network
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
  db_data:

